platform :ios, '7.0'

target 'PaperTrailLumberjackiOSExample' do
	pod "PaperTrailLumberjack", :path => "../.."
end

target 'PaperTrailLumberjackiOSExampleTests' do
	pod "PaperTrailLumberjack", :path => "../.."
end
