platform :osx, '10.7'

target 'PaperTrailLumberjackMacExample' do
	pod "PaperTrailLumberjack", :path => "../.."
end

target 'PaperTrailLumberjackMacExampleTests' do
	pod "PaperTrailLumberjack", :path => "../.."
end
